### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by SemenMartynov** [Sagadeyeva/json-checker#3]
Please create the user documentation and project description (README.md)

**Comment by Sagadeyeva** [comment]
README-file has been added

**Comment by SemenMartynov** [comment]
Please use formated markdown.

**Comment by Sagadeyeva** [comment]
last one README-file now is correct. (had problems with vizualizing copied from example text using markdown, so [THIS](https://github.com/Sagadeyeva/json-checker/blob/master/README.md) is final

**Comment by SemenMartynov** [comment]
It looks good now.
